# basic options
title: test
author: jiale1029
email: tanj0238@e.ntu.edu.sg
description: A wonderful site
twitter_username: chryos1029
github_username:  jiale1029

# Build settings
markdown: kramdown
theme: minima
